# Generated by Django 4.2.6 on 2024-05-29 05:05

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_student_master_native_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_master',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.student_photo_path_path),
        ),
    ]
