# Generated by Django 4.2.6 on 2024-05-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_student_master_passport_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_master',
            name='surname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
