# Generated by Django 5.0.2 on 2024-05-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_student_master_surname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='two_reference',
            old_name='mobile',
            new_name='mobile_contact',
        ),
        migrations.AddField(
            model_name='two_reference',
            name='residence_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
