# Generated by Django 4.2.6 on 2024-05-31 12:39

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_request_edu_loan_fy_request_edu_loan_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request_edu_loan',
            old_name='total_loan_amount',
            new_name='tot_req_loan_amt',
        ),
        migrations.AddField(
            model_name='loan_expense_details',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loan_expense_details',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='loan_expense_details',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan_expense_details',
            name='modified_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loan_expense_details',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='loan_expense_details',
            name='ua',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loandocuments',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loandocuments',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='loandocuments',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loandocuments',
            name='modified_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loandocuments',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='loandocuments',
            name='ua',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='request_edu_loan',
            name='app_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='request_edu_loan',
            name='app_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request_edu_loan',
            name='app_loan_amt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request_edu_loan',
            name='cancl_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request_edu_loan',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='request_edu_loan',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='request_edu_loan',
            name='history_field',
            field=jsonfield.fields.JSONField(default='{}'),
        ),
        migrations.AddField(
            model_name='request_edu_loan',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request_edu_loan',
            name='modified_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='request_edu_loan',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='request_edu_loan',
            name='rej_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='request_edu_loan',
            name='rej_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request_edu_loan',
            name='rej_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request_edu_loan',
            name='ret_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='request_edu_loan',
            name='ret_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request_edu_loan',
            name='return_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request_edu_loan',
            name='ua',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
